# Generated by Django 6.0.3 on 2026-04-02 21:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchRadius',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_radius', models.IntegerField()),
                ('max_radius', models.IntegerField()),
                ('unit', models.CharField(choices=[('KM', 'Kilometers'), ('MI', 'Miles')], default='MI', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(blank=True, default='', max_length=30)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sign', models.CharField(blank=True, default='', max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('NB', 'Non-binary'), ('TF', 'Trans Female'), ('TM', 'Trans Male'), ('O', 'Other')], default='O', max_length=2)),
                ('open_to', models.JSONField(default=list)),
                ('profession', models.CharField(choices=[('SE', 'Self-employed'), ('WFH', 'Work from home'), ('HY', 'Hybrid'), ('IO', 'In-office'), ('UE', 'Unemployed'), ('ST', 'Student')], default='UE', max_length=3)),
                ('bucket', models.JSONField(default=list)),
                ('quick_answers', models.JSONField(default=dict)),
                ('love_give', models.CharField(blank=True, default='', max_length=80)),
                ('love_receive', models.CharField(blank=True, default='', max_length=80)),
                ('photo_verified', models.BooleanField(default=False)),
                ('profile_photo_url', models.URLField(blank=True, default='')),
                ('availability', models.JSONField(default=dict)),
                ('match_radius', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.matchradius')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.profile')),
            ],
        ),
    ]
